//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istecnotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int idnota { get; set; }
        public Nullable<int> num { get; set; }
        public string disciplina { get; set; }
        public Nullable<byte> nota1 { get; set; }
    
        public virtual aluno aluno { get; set; }
    }
}
